apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-db-credentials
type: Opaque
data:
  db: Y2x0dXJlX3Byb2R1Y3Rpb25fZGIK
  user: c3RyZWFtbHl0aWNzLWRiLXVzZXIK
  password: c3RyZWFtbHl0aWNzMjAyMF9kYXRhIQo=